### ISSUE TITLE
Are you running the environment server before running the reformulator code?

### ISSUE THREAD

**Issue by SuryaSg** [google/active-qa#18]
Are you running the environment server before running the reformulator code?

_Originally posted by @graviraja in https://github.com/google/active-qa/issues/15#issuecomment-461702222_

Kindly help me on how to run the environment server before running the reformulator code?
I've also tried changing environment_server_address=None. Still the same issue.

**Comment by graviraja** [comment]
@SuryaSg It is given in the README. Follow the steps: preprocessing, running grpc server and then running the environment.

**Comment by SuryaSg** [comment]
@graviraja  I've done the preprocessing step it was fine, after running Grcp Server, Mine is getting killed. Could you please share the screenshot of Running Grcp Server. Is there any fix for my issue? 
![server_issue](https://user-images.githubusercontent.com/10097003/54509304-2441cb80-496f-11e9-8391-56ed59ea7cbb.png)

**Comment by graviraja** [comment]
@SuryaSg  Which python version you are using?

**Comment by SuryaSg** [comment]
@graviraja  I'm using Python 2.7.15 :: Anaconda, Inc.

Please Suggest working version. Thanks.

**Comment by graviraja** [comment]
@SuryaSg Yeah Python 2.7 will work. Are you running on GPU or CPU ?

**Comment by SuryaSg** [comment]
@graviraja I'm Just running on Intel® Core™ i5-8400 CPU @ 2.80GHz × 6. 
Should I need to use GPU for the same?

**Comment by graviraja** [comment]
@SuryaSg I ran the code on GPU. I haven't tried on CPU.

**Comment by SuryaSg** [comment]
Could you please give me the config necessarily sufficient for running the grcp server?

**Comment by graviraja** [comment]
@SuryaSg No modifications required for running grpc server, If you are using python2.7 and GPU.

**Comment by SuryaSg** [comment]
@graviraja Okays, I'll check for the same. Thanks for being supportive. Tons of Gratitude.
