### ISSUE TITLE
Problem in download of reformulator pretrained model.

### ISSUE THREAD

**Issue by yukioichida** [google/active-qa#29]
I'm trying to download the pretrained model file of reformulator(translate.ckpt-6156696.zip) and returns forbidden access (403).
https://storage.cloud.google.com/pretrained_models/translate.ckpt-6156696.zip

Can you provide a public link for this file?

**Comment by pradeep8500** [comment]
You can download the reformulation checkpoints using readme file, now it's working fine.

**Comment by yukioichida** [comment]
Worked!

Thanks @pradeep8500 .

**Comment by SageAgastya** [comment]
The problem persists, It says "{my account} does not have storage.objects.get access to the Google Cloud Storage object." when I click on the download link.
