### ISSUE TITLE
answers_file is not extracted/provided 

### ISSUE THREAD

**Issue by JunchenJin** [google/active-qa#5]
When running Selector Training section, px.nmt.reformulator_and_selector_training module requires answers files (shown below). However, train_data is not provided in configurations. Neither the answers file is not generated after preprocessing squad data using python -m searchqa.prepro \
--searchqa_dir=$DATA_DIR/SearchQA \
--squad_dir=$SQUAD_DIR.
Could you please give some help on how to fix this issue. 
  questions, annotations, docid_2_answer = read_data(
      questions_file=FLAGS.train_questions,
      annotations_file=FLAGS.train_annotations,
      answers_file=FLAGS.train_data,
      preprocessing_mode=FLAGS.mode)
  dev_questions, dev_annotations, dev_docid_2_answer = read_data(
      questions_file=FLAGS.dev_questions,
      annotations_file=FLAGS.dev_annotations,
      answers_file=FLAGS.dev_data,
      preprocessing_mode=FLAGS.mode,
      max_lines=FLAGS.max_dev_examples)

**Comment by rodrigonogueira4** [comment]
Thanks a lot for finding this. It is fixed now.
