### ISSUE TITLE
Can we use this to generate question and answers from a directory of text files

### ISSUE THREAD

**Issue by Abhi001vj** [google/active-qa#6]
I have not seen this kind of training and inference , can I use just raw text files to get the model to come up with questions. Thus building  a qa bot.

**Comment by rodrigonogueira4** [comment]
If I understood your question correctly, the answer is no because you need a question and a raw document as inputs to the model. The raw document alone is not enough.

**Comment by Abhi001vj** [comment]
Thank you.
