### ISSUE TITLE
How do I know the training is finished for reformulator_and_selector_training

### ISSUE THREAD

**Issue by JunchenJin** [google/active-qa#8]
Hello!

Could you please provide some info when/how do I know training is finished for reformulator_and_selector_training? 
If the training is finished, how can I directly use to trained model for query reformulator?
Could you please provide a trained model for reformulator_and_selector_training as you did for reformulator?

Thanks!

**Comment by rodrigonogueira4** [comment]
1. reformulator_and_selector_training should plateau at ~47.4 F1 score after 1 epoch (or ~5k minibatch updates). Also, you can follow the training progress by lauching tensorboard:
tensorboard --logdir=$OUT_DIR/tensorboard
Then navigate your web browser to http://localhost:6006

2. We will provide code to save/load selector checkpoints soon, along with a fully trained selector checkpoint. If you don't want to wait, you can call load() and save() functions in the px/selector/selector_keras.py accordingly.

**Comment by TambourineMan42** [comment]
@rodrigonogueira4 Did you happen to use 1 epoch for reformulator training too?

**Comment by rodrigonogueira4** [comment]
No, the reformulator takes 20-100 epochs to reach 42.4 F1 on the dev set, which is about a week of training on a single P100 GPU.
